export const enUS = {
  "404Page": {
    back: "Hop back to Home",
    "back.comment": "Back to home button",
    onlyHopper: "There’s only Hopper here",
    "onlyHopper.comment": "Only Hopper",
    oops: "OOPS",
    "oops.comment": "OOPS text",
    pageDoesNotExist: "Looks like the page you’re looking for doesn’t exist :(",
    "pageDoesNotExist.comment": "The page user is looking for does not exist",
    youCanStay: "You can stay to keep him company though",
    "youCanStay.comment": "Whoever came up with this line is cool",
  },
  accountIconButton: {
    myAccount: "My account",
    "myAccount.comment": "My account text",
    profile: "Profile",
    "profile.comment": "profile text",
  },
  calculator: {
    calcVariables: {
      explanation:
        "Type variables in text box (e.g. x=5) or press the button below",
      "explanation.comment": "Explanation for calculator variables",
    },
    equals: "=",
    "equals.comment": "Equal to sign",
    history: {
      explanation: "Type an equation to show history...",
      "explanation.comment": "Explanation for how to show history",
      placeholder: "[insert cool image/space filler here]",
      "placeholder.comment":
        "This is probably going to be removed sometime soon",
    },
  },
  days: {
    monday: "Monday",
    tuesday: "Tuesday",
    wednesday: "Wednesday",
    thursday: "Thursday",
    friday: "Friday",
    saturday: "Saturday",
    sunday: "Sunday",
  },
  desktopHome: {
    recommended: "Recommended",
    "recommended.comment": "Recommended spelled right (For John)",
    schedule: "Schedule",
    "schedule.comment": "Schedule text",
    quickAccess: "Quick Access:",
    "quickAccess.comment": "Title Text for the quick access area",
    viewFullSchedule: "View Full Schedule",
    "viewFullSchedule.comment": "View Full Schedule button",
  },
  errorBoundary: {
    somethingWentWrong: "Something went wrong.",
    "somethingWentWrong.comment": "Something whent wrong text.",
  },
  errorCode: {
    display: "Error Code: {{code}} {{reason}}",
    "display.comment": "Displays the error code in a simple way",
  },
  essayEditor: {
    enableFullscreen: "Please enable fullscreen mode (f) to use",
    "enableFullscreen.comment": "Enable fullscreen mode prompt",
  },
  gasLaws: {
    hi: "Hi!",
    "hi.comment": "Hi!",
    molarity: "Molarity",
    "molarity.comment": "Molarity",
    pressure: "Pressure",
    "pressure.comment": "Pressure",
    solveFor: "Solve For",
    "solveFor.comment": "Solve For text",
    temperature: "Temperature",
    "temperature.comment": "Temperature",
    volume: "Volume",
    "volume.comment": "Volume",
  },
  inviteBuilder: {
    backToSearch: "Back to search",
    "backToSearch.comment": "Back to search text",
    classStart: "Class Start Time",
    "classStart.comment": "Class Start Time title",
    createSchedule: "Create a schedule block",
    "createSchedule.comment": "Create a schedule block title",
    displayDuration: "{{start}} - {{end}} ({{duration}} mins)",
    "displayDuration.comment": "Displays the duration",
    makeSchedule: "Make your own schedule",
    "makeSchedule.comment": "Make your own schedule title",
    scheduleBuilder: "Schedule Builder",
    "scheduleBuilder.comment": "Title for schedule builder",
  },
  keybindEditor: {
    keybinds: {
      calculator: "(c) - calculator",
      "calculator.comment": "Calculator keybind",
      fullscreen: "(f) - fullscreen module",
      "fullscreen.comment": "Fullscreen module keybind",
      nothing: "3: nothing",
      "nothing.comment": "nothing keybind",
    },
    keybindsTitle: "Keybinds:",
    "keybindsTitle.comment": "Keybinds list starter",
  },
  landingPage: {
    placeholder:
      "It looks like you are not signed in! We are currently building our landing page, but if you want to go to the dashboard, click me!",
    "placeholder.comment":
      "Why have you guys not made the landing page yet brug",
  },
  login: {
    login: "Login",
    "login.comment": "Login Text for the login component",
    signIn: "Sign In",
    "signIn.comment": "Signin text for the login component",
  },
  loginPopup: {
    dontHaveAnAccount: "Don't have an account?",
    "dontHaveAnAccount.comment": "Don't have an account text",
    forgotPassword: "Forgot password?",
    "forgotPassword.comment": "Forgot password text",
    login: "Login",
    "login.comment": "Login text",
    signIn: "Sign In",
    "signIn.comment": "Sign in text",
    useHWBounty: "Use your HWBounty Account",
    "useHWBounty.comment": "Use your HWBounty Account text",
  },
  mobileHome: {
    schedule: "Schedule",
    "schedule.comment": "Schedule title",
  },
  navbar: {
    login: "LOGIN",
    "login.comment": "Login prompt",
  },
  newProfile: {
    balance: "Balance",
    "balance.comment": "Balance text",
    handle: "@{{publicID}}",
    "handle.comment": "Formatting for user handle",
    joinedOn: "Joined on",
    "joinedOn.comment": "Joined on text",
    learnAboutCoins: "Learn About Coins",
    "learnAboutCoins.comment": "Learn About Coins prompt",
    NA: "N/A",
    "NA.comment": "School N/A",
    school: "School",
    "school.comment": "School title",
    tags: "Tags:",
    "tags.comment": "Tags",
    userId: "User ID: ",
    "userId.comment": "userID Text",
    whatIsThis: "What is this?",
    "whatIsThis.comment": "What is this title",
  },
  newSchedule: {
    hi: "Hi!",
    "hi.comment": "why?",
  },
  newSignup: {
    checkEmail: "Please check your email for a confimration link. Thank you!",
    "checkEmail.comment": "Check email prompt",
    createAccount: "Create your HWBounty account",
    "createAccount.comment": "Create account prompt",
    enter: "Enter the following below:",
    "enter.comment": "Enter the following prompt",
    name: "HWBounty",
    "name.comment": "HWBounty name",
    next: "Next",
    "next.comment": "Next comment",
    selectAccountType: "Select school account type",
    "selectAccountType.comment": "Select school account type prompt",
    signUp: "Sign Up",
    "signUp.comment": "Sign up prompt",
    signUpWithEmail: "Sign-up with email instead",
    "signUpWithEmail.comment": "Sign up with email instead prompt",
    useSchoolAccount: "Use school account instead",
    "useSchoolAccount.comment": "Use school account instead prompt text",
  },
  profile: {
    hi: "hihiiii",
    "hi.comment": "why",
  },
  queuePage: {
    parenthesis: ")",
    "parenthesis.comment":
      "I honestly don't know what is going on in that file",
  },
  schedule: {
    fetching: "Fetching Schedule Data/ Zoom Links...",
    "fetching.comment": "Fetching text",
    linkSchoology: "Link Schoology Account",
    "linkSchoology.comment": "Link Schoology account button text",
    linkSchoologyPrompt:
      "Seems like you don't have a school account linked! Please link your schoology account to get access to this feature!",
    "linkSchologyPrompt.comment": "Link schoology account prompt text",
    minsFormatting: "{{period}}   {{tSS}}-{{tES}} ({{mins}} mins)",
    "minsFormatting.comment": "Mins Formatting",
    noSchedule:
      "Seems like you dont have a schedule setup! Please go over to the schedules catalog and set a schedule!",
    "noSchedule.comment": "No schedule linked error text",
  },
  schedules: {
    findFormat: "Find the schedule format for your school!",
    "findFormat.comment": "Find the schedule formats prompt text",
    noSchool: "No School Today!",
    "noSchool.comment": "No school text",
    scheduleCatalog: "Schedule Catalog",
    "scheduleCatalog.comment": "Schedule Catalog title text",
    timeSpan: "{{timeStart}}-{{timeEnd}}",
    "timeSpan.comment": "Time Span formatting",
    viewSchedule: "View Schedule",
    "viewSchedule.comment": "View Schedule button text",
  },
  scheduleBuilder: {
    backToSearch: "Back to search",
    "backToSearch.comment": "Back to search text",
    classStartTime: "Class Start Time",
    "classStartTime.comment": "Class Start Time text",
    createSchedule: "Create a schedule block",
    "createSchedule.comment": "Create a schedule block",
    formatMinutes: "{{start}} - {{end}} ({{mins}} mins)",
    "formatMinues.comment": "Format minutes and duration to text",
    makeSchedule: "Make your own schedule",
    "makeSchedule.comment": "Make your own schedule text",
    scheduleBuilder: "Schedule Builder",
    "scheduleBuilder.comment": "Schedule Builder title text",
  },
  schoologyButton: {
    authWithSchoology: "Authenticate With Schoology",
    "authWithSchoology.comment": "Authenticate with schoology button text",
  },
  setSchedule: {
    by: "By:",
    "by.comment": "By text",
    lastUpdated: "Last Updated:",
    "lastUpdated.comment": "Last Updated text",
    noSchool: "No School Today!",
    "noSchool.comment": "No school today text",
    setClasses: "Set Classes",
    "setClasses.comment": "Set Classes text",
  },
  settings: {
    title: "Settings",
    "title.comment": "Settings title",
  },
  sidebar: {
    signOutPrompt: {
      signOutConfirmation: "Are you sure you would like to sign out?",
      "signOutConfirmation.comment": "Signout confirmation",
      signingOutInfo: {
        signingOutClearStart: "Signing out also clears:",
        "signingOutClearStart.comment": "Start of the signing out info",
        signingOutClearPreference: "- Dark mode/light mode preference.",
        "signingOutClearPreference.comment":
          "Tells user that lightmode/darkmode preference will be cleared",
      },
      signOutButtons: {
        no: "No",
        "no.comment": "No button for signout",
        yes: "Yes",
        "yes.comment": "Yes button for signout",
      },
    },
  },
  signInPopup: {
    signIn: "Sign In",
    "signIn.comment": "Sign in popup title text",
  },
  vanityInvite: {
    coinsBonus: "500 Coins Signup Bonus",
    "coinsBonus.comment": "Coin Bonus info text",
    completelyFree: "Completely Free",
    "completelyFree.comment": "Completely Free info text",
    diamond: "♦",
    "diamond.comment": "♦ symbol",
    freePremium: "Free Premium (1 Month)",
    "freePremium.comment": "Free Premium info text",
    go: "Go!",
    "go.comment": "Go button text",
    info: {
      calculators: "Calculators",
      "calculators.comment": "Calculators info",
      homeworkHelp: "Homework Help",
      "homeworkHelp.comment": "Homework Help info",
      schedules: "Schedules",
      "schedules.comment": "Schedules info",
    },
    inviteBy: "Invite by:  ",
    "inviteBy.comment": "Invite by text",
    invitedByWithName: "invited you to join HWBounty - [ {{name}} ]",
    "invitedByWithName.comment": "Invitation line with username",
    noAds: "No Ads for Life",
    "noAds.comment": "No Ads info text",
    perks: "Perks:",
    "perks.comment": "Perks title",
    signUp: "HWBounty Sign Up",
    "signUp.comment": "HWBounty Sign Up prompt",
    tagline: "The modern student’s best friend",
    "tagline.comment": "Tagline",
    usernameFormatting: " ( {{firstName}} {{lastName}} )",
    "usernameFormatting.comment": "Formatting for user invite",
  },
  viewSchedule: {
    by: "By:",
    "by.comment": "By text",
    lastUpdated: "Last Updated:",
    "lastUpdated.comment": "Last Updated text",
    noSchool: "No School Today!",
    "noSchool.comment": "No school text",
  },
  zoomLinks: {
    fetching: "Fetching Zoom Links",
    "fetching.comment": "Fetching zoom links text",
    schoologyNotLinked: "Schoology Not Linked!",
    "schoologyNotLinked.comment": "Schoology not linked error text",
  },
};

export default enUS;
