export const hiIN = {
  '404Page': {
    back: 'Vaapas Home pe jao',
    'back.comment': 'Back to home button',
    onlyHopper: 'Keval Hopper yahaan hai',
    'onlyHopper.comment': 'Only Hopper',
    oops: 'OOPS',
    'oops.comment': 'OOPS text',
    pageDoesNotExist: 'Lagata jo page aap koge rahe hai nahi hai :(',
    'pageDoesNotExist.comment': 'The page user is looking for does not exist',
    youCanStay: 'Aap uske sath rah sakthe hai.',
    'youCanStay.comment': 'Whoever came up with this line is cool',
  },
  accountIconButton: {
    myAccount: 'Mera account',
    'myAccount.comment': 'My account text',
    profile: 'Profile',
    'profile.comment': 'profile text',
  },
  calculator: {
    calcVariables: {
      explanation:
        'Text box mei variables taip karen (e.g. x=5) ya neeche ye button dabaen',
      'explanation.comment': 'Explanation for calculator variables',
    },
    equals: '=',
    'equals.comment': 'Equal to sign',
    history: {
      explanation: 'Ek equation type karne pe tho history dheko...',
      'explanation.comment': 'Explanation for how to show history',
      placeholder: '[insert cool image/space filler here]',
      'placeholder.comment':
        'This is probably going to be removed sometime soon',
    },
  },
  days: {
    monday: 'Somavaar',
    tuesday: 'Mangalavaar',
    wednesday: 'Budhavaar',
    thursday: 'Guruvaar',
    friday: 'Shukravaar',
    saturday: 'Shanivaar',
    sunday: 'Ravivaar',
  },
  desktopHome: {
    recommended: 'Recommended',
    'recommended.comment': 'Recommended spelled right (For John)',
    schedule: 'Schedule',
    'schedule.comment': 'Schedule text',
    quickAccess: 'Quick Access:',
    'quickAccess.comment': 'Title Text for the quick access area',
    viewFullSchedule: 'Full Schedule dheko',
    'viewFullSchedule.comment': 'View Full Schedule button',
  },
  errorBoundary: {
    somethingWentWrong: 'Kuchh galat hoogya.',
    'somethingWentWrong.comment': 'Something whent wrong text.',
  },
  errorCode: {
    display: 'Error Code: {{code}} {{reason}}',
    'display.comment': 'Displays the error code in a simple way',
  },
  essayEditor: {
    enableFullscreen: 'Use karne ke lyai fullscreen mode enable karen (f)',
    'enableFullscreen.comment': 'Enable fullscreen mode prompt',
  },
  gasLaws: {
    hi: 'Hi!',
    'hi.comment': 'Hi!',
    molarity: 'Molarity',
    'molarity.comment': 'Molarity',
    pressure: 'Pressure',
    'pressure.comment': 'Pressure',
    solveFor: 'Solve For',
    'solveFor.comment': 'Solve For text',
    temperature: 'Temperature',
    'temperature.comment': 'Temperature',
    volume: 'Volume',
    'volume.comment': 'Volume',
  },
  inviteBuilder: {
    backToSearch: 'Vaapas search pe jao',
    'backToSearch.comment': 'Back to search text',
    classStart: 'Class Start Time',
    'classStart.comment': 'Class Start Time title',
    createSchedule: 'Ek schedule block banaen',
    'createSchedule.comment': 'Create a schedule block title',
    displayDuration: '{{start}} - {{end}} ({{duration}} mins)',
    'displayDuration.comment': 'Displays the duration',
    makeSchedule: 'Aapna khud ka schedule banaen',
    'makeSchedule.comment': 'Make your own schedule title',
    scheduleBuilder: 'Schedule Builder',
    'scheduleBuilder.comment': 'Title for schedule builder',
  },
  keybindEditor: {
    keybinds: {
      calculator: '(c) - calculator',
      'calculator.comment': 'Calculator keybind',
      fullscreen: '(f) - fullscreen module',
      'fullscreen.comment': 'Fullscreen module keybind',
      nothing: '3: nothing',
      'nothing.comment': 'nothing keybind',
    },
    keybindsTitle: 'Keybinds:',
    'keybindsTitle.comment': 'Keybinds list starter',
  },
  landingPage: {
    placeholder:
      'Lagata aap signed in nahi hai! Hum humara landing page ban raha hai, lekin dashboard dhekhnay ke leiya, yahan click karen!',
    'placeholder.comment':
      'Why have you guys not made the landing page yet brug',
  },
  login: {
    login: 'Login',
    'login.comment': 'Login Text for the login component',
    signIn: 'Sign In',
    'signIn.comment': 'Signin text for the login component',
  },
  loginPopup: {
    dontHaveAnAccount: 'Ek account nahi hai?',
    'dontHaveAnAccount.comment': "Don't have an account text",
    forgotPassword: 'Password bhoola?',
    'forgotPassword.comment': 'Forgot password text',
    login: 'Login',
    'login.comment': 'Login text',
    signIn: 'Sign In',
    'signIn.comment': 'Sign in text',
    useHWBounty: 'Use your HWBounty Account',
    'useHWBounty.comment': 'Use your HWBounty Account text',
  },
  mobileHome: {
    schedule: 'Schedule',
    'schedule.comment': 'Schedule title',
  },
  navbar: {
    login: 'LOGIN',
    'login.comment': 'Login prompt',
  },
  newProfile: {
    balance: 'Balance',
    'balance.comment': 'Balance text',
    handle: '@{{publicID}}',
    'handle.comment': 'Formatting for user handle',
    joinedOn: 'Joined on',
    'joinedOn.comment': 'Joined on text',
    learnAboutCoins: 'Learn About Coins',
    'learnAboutCoins.comment': 'Learn About Coins prompt',
    NA: 'N/A',
    'NA.comment': 'School N/A',
    school: 'School',
    'school.comment': 'School title',
    tags: 'Tags:',
    'tags.comment': 'Tags',
    userId: 'User ID: ',
    'userId.comment': 'userID Text',
    whatIsThis: 'Ye kya hai?',
    'whatIsThis.comment': 'What is this title',
  },
  newSchedule: {
    hi: 'Hi!',
    'hi.comment': 'why?',
  },
  newSignup: {
    checkEmail: 'Please check your email for a confimration link. Thank you!',
    'checkEmail.comment': 'Check email prompt',
    createAccount: 'Aapka HWBounty account banaen',
    'createAccount.comment': 'Create account prompt',
    enter: 'Enter the following below:',
    'enter.comment': 'Enter the following prompt',
    name: 'HWBounty',
    'name.comment': 'HWBounty name',
    next: 'Next',
    'next.comment': 'Next comment',
    selectAccountType: 'Select school account type',
    'selectAccountType.comment': 'Select school account type prompt',
    signUp: 'Sign Up',
    'signUp.comment': 'Sign up prompt',
    signUpWithEmail: 'Sign-up with email instead',
    'signUpWithEmail.comment': 'Sign up with email instead prompt',
    useSchoolAccount: 'Use school account instead',
    'useSchoolAccount.comment': 'Use school account instead prompt text',
  },
  profile: {
    hi: 'hihiiii',
    'hi.comment': 'why',
  },
  queuePage: {
    parenthesis: ')',
    'parenthesis.comment':
      "I honestly don't know what is going on in that file",
  },
  schedule: {
    fetching: 'Schedule Data aur Zoom Links lao...',
    'fetching.comment': 'Fetching text',
    linkSchoology: 'Schoology Account link karen',
    'linkSchoology.comment': 'Link Schoology account button text',
    linkSchoologyPrompt:
      'Lagata aapka account nahi jude hai! Schoology Account link karne pe tho ye feature melega!',
    'linkSchologyPrompt.comment': 'Link schoology account prompt text',
    minsFormatting: '{{period}}   {{tSS}}-{{tES}} ({{mins}} mins)',
    'minsFormatting.comment': 'Mins Formatting',
    noSchedule:
      'Lagata aapka schedule setup nahi hai! Schedules catalog jao fir ek schedule set karen!',
    'noSchedule.comment': 'No schedule linked error text',
  },
  schedules: {
    findFormat: 'Aapka school ka schedule format paana!',
    'findFormat.comment': 'Find the schedule formats prompt text',
    noSchool: 'Aaj school nahi hai!',
    'noSchool.comment': 'No school text',
    scheduleCatalog: 'Schedule Catalog',
    'scheduleCatalog.comment': 'Schedule Catalog title text',
    timeSpan: '{{timeStart}}-{{timeEnd}}',
    'timeSpan.comment': 'Time Span formatting',
    viewSchedule: 'Schedule dekho',
    'viewSchedule.comment': 'View Schedule button text',
  },
  scheduleBuilder: {
    backToSearch: 'Vaapas search pe jao',
    'backToSearch.comment': 'Back to search text',
    classStartTime: 'Class Start Time',
    'classStartTime.comment': 'Class Start Time text',
    createSchedule: 'Ek schedule block banaen',
    'createSchedule.comment': 'Create a schedule block',
    formatMinutes: '{{start}} - {{end}} ({{mins}} mins)',
    'formatMinues.comment': 'Format minutes and duration to text',
    makeSchedule: 'Aapna khud ka schedule banaen',
    'makeSchedule.comment': 'Make your own schedule text',
    scheduleBuilder: 'Schedule Builder',
    'scheduleBuilder.comment': 'Schedule Builder title text',
  },
  schoologyButton: {
    authWithSchoology: 'Authenticate With Schoology',
    'authWithSchoology.comment': 'Authenticate with schoology button text',
  },
  setSchedule: {
    by: 'By:',
    'by.comment': 'By text',
    lastUpdated: 'Last Updated:',
    'lastUpdated.comment': 'Last Updated text',
    noSchool: 'Aaj school nahi hai!',
    'noSchool.comment': 'No school today text',
    setClasses: 'Set Classes',
    'setClasses.comment': 'Set Classes text',
  },
  settings: {
    darkModeLabel: 'Dark Mode :)',
    'darkModeLabel.comment': 'Dark Mode toggle label text',
    language: 'Language Settings',
    'language.comment': 'Language settings area title',
    title: 'Settings',
    'title.comment': 'Settings title',
  },
  sidebar: {
    signOutPrompt: {
      signOutConfirmation: 'Are you sure you would like to sign out?',
      'signOutConfirmation.comment': 'Signout confirmation',
      signingOutInfo: {
        signingOutClearStart: 'Signing out also clears:',
        'signingOutClearStart.comment': 'Start of the signing out info',
        signingOutClearPreference: '- Dark mode/light mode preference.',
        'signingOutClearPreference.comment':
          'Tells user that lightmode/darkmode preference will be cleared',
      },
      signOutButtons: {
        no: 'Nahi',
        'no.comment': 'No button for signout',
        yes: 'Haan',
        'yes.comment': 'Yes button for signout',
      },
    },
  },
  signInPopup: {
    signIn: 'Sign In',
    'signIn.comment': 'Sign in popup title text',
  },
  vanityInvite: {
    coinsBonus: '500 Coins Signup Bonus',
    'coinsBonus.comment': 'Coin Bonus info text',
    completelyFree: 'Completely Free',
    'completelyFree.comment': 'Completely Free info text',
    diamond: '♦',
    'diamond.comment': '♦ symbol',
    freePremium: 'Free Premium (1 Month)',
    'freePremium.comment': 'Free Premium info text',
    go: 'Go!',
    'go.comment': 'Go button text',
    useAnonymousMode: 'Use without signup',
    'useAnonymousMode.comment': 'Anonymous mode info text',

    info: {
      calculators: 'Calculators',
      'calculators.comment': 'Calculators info',
      homeworkHelp: 'Homework Help',
      'homeworkHelp.comment': 'Homework Help info',
      schedules: 'Schedules',
      'schedules.comment': 'Schedules info',
    },
    inviteBy: 'Invite by: ',
    'inviteBy.comment': 'Invite by text',
    invitedByWithName: 'invited you to join HWBounty - [ {{name}} ]',
    'invitedByWithName.comment': 'Invitation line with username',
    noAds: 'No Ads for Life',
    'noAds.comment': 'No Ads info text',
    perks: 'Perks:',
    'perks.comment': 'Perks title',
    signUp: 'HWBounty Sign Up',
    'signUp.comment': 'HWBounty Sign Up prompt',
    tagline: 'modern student ka best friend hai',
    'tagline.comment': 'Tagline',
    usernameFormatting: ' ( {{firstName}} {{lastName}} )',
    'usernameFormatting.comment': 'Formatting for user invite',
  },
  viewSchedule: {
    by: 'By:',
    'by.comment': 'By text',
    lastUpdated: 'Last Updated:',
    'lastUpdated.comment': 'Last Updated text',
    noSchool: 'Aaj school nahi hai!',
    'noSchool.comment': 'No school text',
  },
  zoomLinks: {
    fetching: 'Zoom links lao',
    'fetching.comment': 'Fetching zoom links text',
    schoologyNotLinked: 'Schoology Nahi Jude Hai!',
    'schoologyNotLinked.comment': 'Schoology not linked error text',
  },
};

export const NAME = 'Hindi';

export default hiIN;
